CREATE TABLE PESSOA (
    ID_PESSOA INT PRIMARY KEY AUTO_INCREMENT, 
    PESSOA VARCHAR(30) NOT NULL, 
    SETOR VARCHAR(20) NOT NULL
);

CREATE TABLE MAQUINA (
    ID_MAQUINA INT PRIMARY KEY AUTO_INCREMENT, 
    MAQUINA VARCHAR(10) NOT NULL 
);

CREATE TABLE NIVEL (
    ID_NIVEL INT PRIMARY KEY AUTO_INCREMENT, 
    NIVEL VARCHAR(15) NOT NULL, 
    SEVERIDADE VARCHAR(15)
);

CREATE TABLE CHAMADO (
    ID_CHAMADO INT PRIMARY KEY AUTO_INCREMENT, 
    PESSOA INT NOT NULL, 
    MAQUINA INT NOT NULL, 
    SEVERIDADE INT NOT NULL, 
    DATA_ABERTURA TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, 
    DATA_FECHAMENTO TIMESTAMP NOT NULL, 
    DESCRICAO VARCHAR(200)
);

ALTER TABLE CHAMADO ADD CONSTRAINT FK_PESSOA FOREIGN KEY (PESSOA) REFERENCES PESSOA(ID_PESSOA);
ALTER TABLE CHAMADO ADD CONSTRAINT FK_MAQUINA FOREIGN KEY (MAQUINA) REFERENCES MAQUINA(ID_MAQUINA);
ALTER TABLE CHAMADO ADD CONSTRAINT FK_SEVERIDADE FOREIGN KEY (SEVERIDADE) REFERENCES NIVEL(ID_NIVEL);